services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "29000:9000"
    environment:
      - PORT=9000
      # Add other environment variables as needed
    env_file:
      - .env
    volumes:
      - ./geodini:/app/geodini
      - ./data:/app/data
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "9000", "--reload"] 

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "20080:80"
    volumes:
      - ./frontend-local:/usr/share/nginx/html
    depends_on:
      - api
  
  # database:
  #   image: postgis/postgis:17-3.4
  #   ports:
  #     - "15432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   networks:
  #     - default
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data
