FROM python:3.11-slim

# Install DuckDB CLI
RUN apt-get update && apt-get install -y wget unzip && \
    wget -O /tmp/duckdb https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip && \
    unzip /tmp/duckdb -d /usr/local/bin/ && \
    chmod +x /usr/local/bin/duckdb && \
    rm -rf /tmp/duckdb && \
    apt-get remove --purge -y wget unzip && apt-get autoremove -y && apt-get clean;
