apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "geodini.fullname" . }}-api
  labels:
    {{- include "geodini.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  serviceName: {{ include "geodini.fullname" . }}-api-headless # For stable pod identities
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "geodini.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "geodini.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "geodini.serviceAccountName" . }}
      securityContext:
        {}
      volumes:
        - name: temp-dir
          emptyDir: {}
      {{- if .Values.api.initContainer.ingest.enabled }}
      initContainers:
        - name: init-ingest-data
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command: {{ toJson .Values.api.initContainer.ingest.command }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.api.env.POSTGRES_HOST | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.api.env.POSTGRES_PORT | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "geodini.fullname" . }}-geodini-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "geodini.fullname" . }}-geodini-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "geodini.fullname" . }}-geodini-secret
                  key: POSTGRES_DB
            - name: DATA_PATH
              value: /tmp/data
            {{- if .Values.api.initContainer.ingest.forceRecreate }}
            - name: FORCE_RECREATE
              value: "true"
            {{- end }}
          volumeMounts:
            - name: temp-dir
              mountPath: /tmp
          resources:
            {{- toYaml .Values.api.initContainer.ingest.resources | nindent 12 }}
      {{- end }}
      containers:
        - name: api
          securityContext:
            {}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command:
            - "uvicorn"
            - "geodini.api.api:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - {{ .Values.api.port | quote }}
            - "--workers"
            - "4"
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.api.port | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.api.env.POSTGRES_HOST | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.api.env.POSTGRES_PORT | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "geodini.fullname" . }}-geodini-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "geodini.fullname" . }}-geodini-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "geodini.fullname" . }}-geodini-secret
                  key: POSTGRES_DB
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "geodini.fullname" . }}-geodini-secret
                  key: OPENAI_API_KEY
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 45
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 20
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - name: temp-dir
              mountPath: /tmp
