apiVersion: v1
kind: Service
metadata:
  name: {{ include "geodini.fullname" . }}-api-headless
  labels:
    {{- include "geodini.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  clusterIP: None # Defines this as a Headless Service
  ports:
    - port: {{ .Values.api.port }} # Port the service will expose (same as container port for headless)
      targetPort: http # Name of the port in the Pod spec
      protocol: TCP
      name: http
  selector:
    {{- include "geodini.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
