# Default values for geodini-chart.
replicaCount: 1

api:
  image:
    repository: ghcr.io/sunu/geodini/api
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      memory: "4Gi"
  port: 9000
  service:
    type: ClusterIP
    port: 9000
  env:
    PORT: "9000"
    POSTGRES_HOST: "geodini-postgres" # Service name of our postgres
    POSTGRES_PORT: "5432"
    REDIS_HOST: "geodini-redis-master" # Service name of Redis subchart
    REDIS_PORT: "6379"
    REDIS_DB: "0"
    # POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB are taken from a secret
  initContainer:
    ingest:
      command: ["python", "geodini/ingest.py"]
      resources:
        requests:
          memory: "2Gi"
        limits:
          memory: "4Gi"
      forceRecreate: false

# Frontend (Streamlit) configuration
frontend:
  enabled: false  # Set to true to enable Streamlit frontend
  image:
    repository: ghcr.io/sunu/geodini/api  # Same image as API
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  port: 8501
  service:
    type: ClusterIP
    port: 8501
  env:
    API_URL: "http://geodini-api:9000"  # Internal API service URL

# PostgreSQL/PostGIS configuration
postgres:
  enabled: true
  image:
    repository: postgis/postgis
    tag: "16-3.4" # Using 16 as 17 is not yet in postgis/postgis official images
    pullPolicy: IfNotPresent
  port: 5432
  service:
    type: ClusterIP # Internal service
    port: 5432
  # user, password, database configured in 'secrets'
  persistence:
    enabled: true
    storageClassName: "" # Or your specific storage class
    accessModes:
      - ReadWriteOnce
    size: 40Gi # Adjust as needed

# Redis subchart configuration
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: "" # Or your specific storage class
      size: 8Gi # Adjust as needed
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  replica:
    replicaCount: 0 # Disable replicas for simplicity

ingress:
  enabled: false
  className: "nginx" # Or your ingress controller's class name
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod # Example for cert-manager

  # API Ingress Configuration
  apiHost: "api.geodini.local" # Placeholder, e.g., api.yourdomain.com
  
  # Frontend Ingress Configuration (only used if frontend.enabled is true)
  frontendHost: "geodini.local" # Placeholder, e.g., geodini.yourdomain.com

  # Common TLS configuration.
  # You can define one or more secrets.
  # If you have separate certs for frontendHost and apiHost, list them here.
  # If you have a wildcard cert covering both, one entry is sufficient.
  tls: []
  # Example for separate certs:
  # - secretName: geodini-api-tls
  #   hosts:
  #     - api.geodini.local # Must match ingress.apiHost
  # Example for a wildcard cert:
  # - secretName: geodini-wildcard-tls
  #   hosts:
  #     - api.geodini.local

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

# Centralized secrets
secrets:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "changeme" # IMPORTANT: Change for production
  POSTGRES_DB: "postgres"
  OPENAI_API_KEY: "YOUR_OPENAI_API_KEY_HERE" # IMPORTANT: Change for production
