apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geodini.fullname" . }}-geodini-secret
  labels:
    {{- include "geodini.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}
  POSTGRES_DB: {{ .Values.secrets.POSTGRES_DB | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | b64enc | quote }}
